version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: credit-postgres
    environment:
      POSTGRES_DB: creditDB
      POSTGRES_USER: credit
      POSTGRES_PASSWORD: credit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U credit -d creditDB"]
      interval: 5s
      timeout: 3s
      retries: 10
  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  app:
    build: .
    container_name: credit-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/creditDB
      SPRING_DATASOURCE_USERNAME: credit
      SPRING_DATASOURCE_PASSWORD: credit
      EXTERNAL_FRANKFURTER_URL: https://api.frankfurter.dev/v1
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"